import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";
import { DirectionProvider } from "@/components/ui/direction";
import { ThemeProvider } from "@/components/theme-provider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const almarai = Almarai({
  variable: "--font-almarai",
  subsets: ["arabic"],
  weight: ["300", "400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const queryClient = new QueryClient()

  return (
    <html lang="en">
      <body
        className={`${almarai.variable} ${almarai.variable} antialiased`}
        dir="rtl"
      >
        <QueryClientProvider client={queryClient}>


          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <DirectionProvider dir="rtl">{children}</DirectionProvider>
          </ThemeProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
